/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables

import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.indexes.ADMINISTRATOR_USER_ID_INDEX
import com.emented.printingstudio.jooq.keys.ADMINISTRATOR_PKEY
import com.emented.printingstudio.jooq.keys.ADMINISTRATOR_USER_ID_KEY
import com.emented.printingstudio.jooq.keys.ADMINISTRATOR__ADMINISTRATOR_USER_ID_FKEY
import com.emented.printingstudio.jooq.tables.records.AdministratorRecord
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Administrator(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AdministratorRecord>?,
    aliased: Table<AdministratorRecord>?,
    parameters: Array<Field<*>?>?,
) : TableImpl<AdministratorRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
) {
    companion object {

        /**
         * The reference instance of <code>public.administrator</code>
         */
        val ADMINISTRATOR = Administrator()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AdministratorRecord> = AdministratorRecord::class.java

    /**
     * The column <code>public.administrator.id</code>.
     */
    val ID: TableField<AdministratorRecord, Long?> =
        createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.administrator.user_id</code>.
     */
    val USER_ID: TableField<AdministratorRecord, Long?> =
        createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.administrator.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<AdministratorRecord, OffsetDateTime?> =
        createField(DSL.name("creation_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.administrator.update_timestamp</code>.
     */
    val UPDATE_TIMESTAMP: TableField<AdministratorRecord, OffsetDateTime?> =
        createField(DSL.name("update_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AdministratorRecord>?) : this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AdministratorRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        aliased,
        parameters,
    )

    /**
     * Create an aliased <code>public.administrator</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.administrator</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.administrator</code> table reference
     */
    constructor() : this(DSL.name("administrator"), null)

    constructor(
        child: Table<out Record>,
        key: ForeignKey<out Record, AdministratorRecord>,
    ) : this(Internal.createPathAlias(child, key), child, key, ADMINISTRATOR, null)

    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(ADMINISTRATOR_USER_ID_INDEX)
    override fun getIdentity(): Identity<AdministratorRecord, Long?> =
        super.getIdentity() as Identity<AdministratorRecord, Long?>

    override fun getPrimaryKey(): UniqueKey<AdministratorRecord> = ADMINISTRATOR_PKEY
    override fun getKeys(): List<UniqueKey<AdministratorRecord>> = listOf(ADMINISTRATOR_PKEY, ADMINISTRATOR_USER_ID_KEY)
    override fun getReferences(): List<ForeignKey<AdministratorRecord, *>> =
        listOf(ADMINISTRATOR__ADMINISTRATOR_USER_ID_FKEY)

    private lateinit var _user: User
    fun user(): User {
        if (!this::_user.isInitialized) {
            _user = User(this, ADMINISTRATOR__ADMINISTRATOR_USER_ID_FKEY)
        }

        return _user
    }

    override fun `as`(alias: String): Administrator = Administrator(DSL.name(alias), this)
    override fun `as`(alias: Name): Administrator = Administrator(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Administrator = Administrator(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Administrator = Administrator(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Long?, Long?, OffsetDateTime?, OffsetDateTime?> =
        super.fieldsRow() as Row4<Long?, Long?, OffsetDateTime?, OffsetDateTime?>
}
