/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.keys.AVAILABILITY_STATUS_PKEY
import com.emented.printingstudio.jooq.keys.AVAILABILITY_STATUS_VALUE_KEY
import com.emented.printingstudio.jooq.keys.MATERIAL__MATERIAL_AVAILABILITY_STATUS_FKEY
import com.emented.printingstudio.jooq.tables.Material.MaterialPath
import com.emented.printingstudio.jooq.tables.records.AvailabilityStatusRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AvailabilityStatus(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AvailabilityStatusRecord>?,
    parentPath: InverseForeignKey<out Record, AvailabilityStatusRecord>?,
    aliased: Table<AvailabilityStatusRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AvailabilityStatusRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.availability_status</code>
         */
        val AVAILABILITY_STATUS: AvailabilityStatus = AvailabilityStatus()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AvailabilityStatusRecord> = AvailabilityStatusRecord::class.java

    /**
     * The column <code>public.availability_status.id</code>.
     */
    val ID: TableField<AvailabilityStatusRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.availability_status.value</code>.
     */
    val VALUE: TableField<AvailabilityStatusRecord, String?> = createField(DSL.name("value"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AvailabilityStatusRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AvailabilityStatusRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AvailabilityStatusRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.availability_status</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.availability_status</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.availability_status</code> table reference
     */
    constructor(): this(DSL.name("availability_status"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AvailabilityStatusRecord>?, parentPath: InverseForeignKey<out Record, AvailabilityStatusRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, AVAILABILITY_STATUS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AvailabilityStatusPath : AvailabilityStatus, Path<AvailabilityStatusRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AvailabilityStatusRecord>?, parentPath: InverseForeignKey<out Record, AvailabilityStatusRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AvailabilityStatusRecord>): super(alias, aliased)
        override fun `as`(alias: String): AvailabilityStatusPath = AvailabilityStatusPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AvailabilityStatusPath = AvailabilityStatusPath(alias, this)
        override fun `as`(alias: Table<*>): AvailabilityStatusPath = AvailabilityStatusPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<AvailabilityStatusRecord, Long?> = super.getIdentity() as Identity<AvailabilityStatusRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<AvailabilityStatusRecord> = AVAILABILITY_STATUS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<AvailabilityStatusRecord>> = listOf(AVAILABILITY_STATUS_VALUE_KEY)

    private lateinit var _material: MaterialPath

    /**
     * Get the implicit to-many join path to the <code>public.material</code>
     * table
     */
    fun material(): MaterialPath {
        if (!this::_material.isInitialized)
            _material = MaterialPath(this, null, MATERIAL__MATERIAL_AVAILABILITY_STATUS_FKEY.inverseKey)

        return _material;
    }

    val material: MaterialPath
        get(): MaterialPath = material()
    override fun `as`(alias: String): AvailabilityStatus = AvailabilityStatus(DSL.name(alias), this)
    override fun `as`(alias: Name): AvailabilityStatus = AvailabilityStatus(alias, this)
    override fun `as`(alias: Table<*>): AvailabilityStatus = AvailabilityStatus(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AvailabilityStatus = AvailabilityStatus(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AvailabilityStatus = AvailabilityStatus(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AvailabilityStatus = AvailabilityStatus(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AvailabilityStatus = AvailabilityStatus(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AvailabilityStatus = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AvailabilityStatus = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AvailabilityStatus = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AvailabilityStatus = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AvailabilityStatus = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AvailabilityStatus = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AvailabilityStatus = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AvailabilityStatus = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AvailabilityStatus = where(DSL.notExists(select))
}
