/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.indexes.CLID
import com.emented.printingstudio.jooq.keys.CAR_PKEY
import com.emented.printingstudio.jooq.keys.CAR__CAR_CLIENT_ID_FKEY
import com.emented.printingstudio.jooq.tables.Client.ClientPath
import com.emented.printingstudio.jooq.tables.records.CarRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Car(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CarRecord>?,
    parentPath: InverseForeignKey<out Record, CarRecord>?,
    aliased: Table<CarRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CarRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.car</code>
         */
        val CAR: Car = Car()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CarRecord> = CarRecord::class.java

    /**
     * The column <code>public.car.id</code>.
     */
    val ID: TableField<CarRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.car.name</code>.
     */
    val NAME: TableField<CarRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.car.client_id</code>.
     */
    val CLIENT_ID: TableField<CarRecord, Long?> = createField(DSL.name("client_id"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CarRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CarRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CarRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.car</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.car</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.car</code> table reference
     */
    constructor(): this(DSL.name("car"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CarRecord>?, parentPath: InverseForeignKey<out Record, CarRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CAR, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CarPath : Car, Path<CarRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CarRecord>?, parentPath: InverseForeignKey<out Record, CarRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CarRecord>): super(alias, aliased)
        override fun `as`(alias: String): CarPath = CarPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CarPath = CarPath(alias, this)
        override fun `as`(alias: Table<*>): CarPath = CarPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(CLID)
    override fun getIdentity(): Identity<CarRecord, Int?> = super.getIdentity() as Identity<CarRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<CarRecord> = CAR_PKEY
    override fun getReferences(): List<ForeignKey<CarRecord, *>> = listOf(CAR__CAR_CLIENT_ID_FKEY)

    private lateinit var _client: ClientPath

    /**
     * Get the implicit join path to the <code>public.client</code> table.
     */
    fun client(): ClientPath {
        if (!this::_client.isInitialized)
            _client = ClientPath(this, CAR__CAR_CLIENT_ID_FKEY, null)

        return _client;
    }

    val client: ClientPath
        get(): ClientPath = client()
    override fun `as`(alias: String): Car = Car(DSL.name(alias), this)
    override fun `as`(alias: Name): Car = Car(alias, this)
    override fun `as`(alias: Table<*>): Car = Car(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Car = Car(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Car = Car(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Car = Car(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Car = Car(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Car = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Car = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Car = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Car = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Car = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Car = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Car = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Car = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Car = where(DSL.notExists(select))
}
