/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.keys.CAR__CAR_CLIENT_ID_FKEY
import com.emented.printingstudio.jooq.keys.CLIENT_PKEY
import com.emented.printingstudio.jooq.tables.Car.CarPath
import com.emented.printingstudio.jooq.tables.records.ClientRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Client(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ClientRecord>?,
    parentPath: InverseForeignKey<out Record, ClientRecord>?,
    aliased: Table<ClientRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ClientRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.client</code>
         */
        val CLIENT: Client = Client()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ClientRecord> = ClientRecord::class.java

    /**
     * The column <code>public.client.id</code>.
     */
    val ID: TableField<ClientRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.client.name</code>.
     */
    val NAME: TableField<ClientRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<ClientRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ClientRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ClientRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.client</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.client</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.client</code> table reference
     */
    constructor(): this(DSL.name("client"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ClientRecord>?, parentPath: InverseForeignKey<out Record, ClientRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CLIENT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ClientPath : Client, Path<ClientRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ClientRecord>?, parentPath: InverseForeignKey<out Record, ClientRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ClientRecord>): super(alias, aliased)
        override fun `as`(alias: String): ClientPath = ClientPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ClientPath = ClientPath(alias, this)
        override fun `as`(alias: Table<*>): ClientPath = ClientPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<ClientRecord, Int?> = super.getIdentity() as Identity<ClientRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<ClientRecord> = CLIENT_PKEY

    private lateinit var _car: CarPath

    /**
     * Get the implicit to-many join path to the <code>public.car</code> table
     */
    fun car(): CarPath {
        if (!this::_car.isInitialized)
            _car = CarPath(this, null, CAR__CAR_CLIENT_ID_FKEY.inverseKey)

        return _car;
    }

    val car: CarPath
        get(): CarPath = car()
    override fun `as`(alias: String): Client = Client(DSL.name(alias), this)
    override fun `as`(alias: Name): Client = Client(alias, this)
    override fun `as`(alias: Table<*>): Client = Client(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Client = Client(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Client = Client(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Client = Client(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Client = Client(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Client = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Client = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Client = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Client = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Client = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Client = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Client = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Client = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Client = where(DSL.notExists(select))
}
