/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.indexes.CUSTOMER_USER_ID_INDEX
import com.emented.printingstudio.jooq.keys.CUSTOMER_PKEY
import com.emented.printingstudio.jooq.keys.CUSTOMER_SOCIAL_NETWORK__CUSTOMER_SOCIAL_NETWORK_CUSTOMER_ID_FKEY
import com.emented.printingstudio.jooq.keys.CUSTOMER_USER_ID_KEY
import com.emented.printingstudio.jooq.keys.CUSTOMER__CUSTOMER_BUSINESS_INFO_ID_FKEY
import com.emented.printingstudio.jooq.keys.CUSTOMER__CUSTOMER_USER_ID_FKEY
import com.emented.printingstudio.jooq.keys.ORDER__ORDER_CUSTOMER_ID_FKEY
import com.emented.printingstudio.jooq.tables.BusinessInfo.BusinessInfoPath
import com.emented.printingstudio.jooq.tables.CustomerSocialNetwork.CustomerSocialNetworkPath
import com.emented.printingstudio.jooq.tables.Order.OrderPath
import com.emented.printingstudio.jooq.tables.SocialNetwork.SocialNetworkPath
import com.emented.printingstudio.jooq.tables.User.UserPath
import com.emented.printingstudio.jooq.tables.records.CustomerRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Customer(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CustomerRecord>?,
    parentPath: InverseForeignKey<out Record, CustomerRecord>?,
    aliased: Table<CustomerRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CustomerRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.customer</code>
         */
        val CUSTOMER: Customer = Customer()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CustomerRecord> = CustomerRecord::class.java

    /**
     * The column <code>public.customer.id</code>.
     */
    val ID: TableField<CustomerRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.customer.user_id</code>.
     */
    val USER_ID: TableField<CustomerRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.customer.business_info_id</code>.
     */
    val BUSINESS_INFO_ID: TableField<CustomerRecord, Long?> = createField(DSL.name("business_info_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.customer.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<CustomerRecord, OffsetDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.customer.update_timestamp</code>.
     */
    val UPDATE_TIMESTAMP: TableField<CustomerRecord, OffsetDateTime?> = createField(DSL.name("update_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CustomerRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CustomerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CustomerRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.customer</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.customer</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.customer</code> table reference
     */
    constructor(): this(DSL.name("customer"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CustomerRecord>?, parentPath: InverseForeignKey<out Record, CustomerRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CUSTOMER, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CustomerPath : Customer, Path<CustomerRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CustomerRecord>?, parentPath: InverseForeignKey<out Record, CustomerRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CustomerRecord>): super(alias, aliased)
        override fun `as`(alias: String): CustomerPath = CustomerPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CustomerPath = CustomerPath(alias, this)
        override fun `as`(alias: Table<*>): CustomerPath = CustomerPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(CUSTOMER_USER_ID_INDEX)
    override fun getIdentity(): Identity<CustomerRecord, Long?> = super.getIdentity() as Identity<CustomerRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<CustomerRecord> = CUSTOMER_PKEY
    override fun getUniqueKeys(): List<UniqueKey<CustomerRecord>> = listOf(CUSTOMER_USER_ID_KEY)
    override fun getReferences(): List<ForeignKey<CustomerRecord, *>> = listOf(CUSTOMER__CUSTOMER_USER_ID_FKEY, CUSTOMER__CUSTOMER_BUSINESS_INFO_ID_FKEY)

    private lateinit var _user: UserPath

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    fun user(): UserPath {
        if (!this::_user.isInitialized)
            _user = UserPath(this, CUSTOMER__CUSTOMER_USER_ID_FKEY, null)

        return _user;
    }

    val user: UserPath
        get(): UserPath = user()

    private lateinit var _businessInfo: BusinessInfoPath

    /**
     * Get the implicit join path to the <code>public.business_info</code>
     * table.
     */
    fun businessInfo(): BusinessInfoPath {
        if (!this::_businessInfo.isInitialized)
            _businessInfo = BusinessInfoPath(this, CUSTOMER__CUSTOMER_BUSINESS_INFO_ID_FKEY, null)

        return _businessInfo;
    }

    val businessInfo: BusinessInfoPath
        get(): BusinessInfoPath = businessInfo()

    private lateinit var _customerSocialNetwork: CustomerSocialNetworkPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.customer_social_network</code> table
     */
    fun customerSocialNetwork(): CustomerSocialNetworkPath {
        if (!this::_customerSocialNetwork.isInitialized)
            _customerSocialNetwork = CustomerSocialNetworkPath(this, null, CUSTOMER_SOCIAL_NETWORK__CUSTOMER_SOCIAL_NETWORK_CUSTOMER_ID_FKEY.inverseKey)

        return _customerSocialNetwork;
    }

    val customerSocialNetwork: CustomerSocialNetworkPath
        get(): CustomerSocialNetworkPath = customerSocialNetwork()

    private lateinit var _order: OrderPath

    /**
     * Get the implicit to-many join path to the <code>public.order</code> table
     */
    fun order(): OrderPath {
        if (!this::_order.isInitialized)
            _order = OrderPath(this, null, ORDER__ORDER_CUSTOMER_ID_FKEY.inverseKey)

        return _order;
    }

    val order: OrderPath
        get(): OrderPath = order()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.social_network</code> table
     */
    val socialNetwork: SocialNetworkPath
        get(): SocialNetworkPath = customerSocialNetwork().socialNetwork()
    override fun `as`(alias: String): Customer = Customer(DSL.name(alias), this)
    override fun `as`(alias: Name): Customer = Customer(alias, this)
    override fun `as`(alias: Table<*>): Customer = Customer(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Customer = Customer(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Customer = Customer(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Customer = Customer(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Customer = Customer(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Customer = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Customer = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Customer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Customer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Customer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Customer = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Customer = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Customer = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Customer = where(DSL.notExists(select))
}
