/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.indexes.DELIVERY_TYPE_STATUS_INDEX
import com.emented.printingstudio.jooq.keys.DELIVERY_PKEY
import com.emented.printingstudio.jooq.keys.DELIVERY__DELIVERY_STATUS_FKEY
import com.emented.printingstudio.jooq.keys.DELIVERY__DELIVERY_TYPE_FKEY
import com.emented.printingstudio.jooq.keys.ORDER__ORDER_DELIVERY_ID_FKEY
import com.emented.printingstudio.jooq.tables.DeliveryStatus.DeliveryStatusPath
import com.emented.printingstudio.jooq.tables.DeliveryType.DeliveryTypePath
import com.emented.printingstudio.jooq.tables.Order.OrderPath
import com.emented.printingstudio.jooq.tables.records.DeliveryRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Delivery(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, DeliveryRecord>?,
    parentPath: InverseForeignKey<out Record, DeliveryRecord>?,
    aliased: Table<DeliveryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<DeliveryRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.delivery</code>
         */
        val DELIVERY: Delivery = Delivery()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DeliveryRecord> = DeliveryRecord::class.java

    /**
     * The column <code>public.delivery.id</code>.
     */
    val ID: TableField<DeliveryRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.delivery.type</code>.
     */
    val TYPE: TableField<DeliveryRecord, Long?> = createField(DSL.name("type"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.delivery.status</code>.
     */
    val STATUS: TableField<DeliveryRecord, Long?> = createField(DSL.name("status"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.delivery.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<DeliveryRecord, OffsetDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.delivery.update_timestamp</code>.
     */
    val UPDATE_TIMESTAMP: TableField<DeliveryRecord, OffsetDateTime?> = createField(DSL.name("update_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<DeliveryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<DeliveryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<DeliveryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.delivery</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.delivery</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.delivery</code> table reference
     */
    constructor(): this(DSL.name("delivery"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DeliveryRecord>?, parentPath: InverseForeignKey<out Record, DeliveryRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, DELIVERY, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class DeliveryPath : Delivery, Path<DeliveryRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DeliveryRecord>?, parentPath: InverseForeignKey<out Record, DeliveryRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<DeliveryRecord>): super(alias, aliased)
        override fun `as`(alias: String): DeliveryPath = DeliveryPath(DSL.name(alias), this)
        override fun `as`(alias: Name): DeliveryPath = DeliveryPath(alias, this)
        override fun `as`(alias: Table<*>): DeliveryPath = DeliveryPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(DELIVERY_TYPE_STATUS_INDEX)
    override fun getIdentity(): Identity<DeliveryRecord, Long?> = super.getIdentity() as Identity<DeliveryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<DeliveryRecord> = DELIVERY_PKEY
    override fun getReferences(): List<ForeignKey<DeliveryRecord, *>> = listOf(DELIVERY__DELIVERY_TYPE_FKEY, DELIVERY__DELIVERY_STATUS_FKEY)

    private lateinit var _deliveryType: DeliveryTypePath

    /**
     * Get the implicit join path to the <code>public.delivery_type</code>
     * table.
     */
    fun deliveryType(): DeliveryTypePath {
        if (!this::_deliveryType.isInitialized)
            _deliveryType = DeliveryTypePath(this, DELIVERY__DELIVERY_TYPE_FKEY, null)

        return _deliveryType;
    }

    val deliveryType: DeliveryTypePath
        get(): DeliveryTypePath = deliveryType()

    private lateinit var _deliveryStatus: DeliveryStatusPath

    /**
     * Get the implicit join path to the <code>public.delivery_status</code>
     * table.
     */
    fun deliveryStatus(): DeliveryStatusPath {
        if (!this::_deliveryStatus.isInitialized)
            _deliveryStatus = DeliveryStatusPath(this, DELIVERY__DELIVERY_STATUS_FKEY, null)

        return _deliveryStatus;
    }

    val deliveryStatus: DeliveryStatusPath
        get(): DeliveryStatusPath = deliveryStatus()

    private lateinit var _order: OrderPath

    /**
     * Get the implicit to-many join path to the <code>public.order</code> table
     */
    fun order(): OrderPath {
        if (!this::_order.isInitialized)
            _order = OrderPath(this, null, ORDER__ORDER_DELIVERY_ID_FKEY.inverseKey)

        return _order;
    }

    val order: OrderPath
        get(): OrderPath = order()
    override fun `as`(alias: String): Delivery = Delivery(DSL.name(alias), this)
    override fun `as`(alias: Name): Delivery = Delivery(alias, this)
    override fun `as`(alias: Table<*>): Delivery = Delivery(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Delivery = Delivery(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Delivery = Delivery(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Delivery = Delivery(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Delivery = Delivery(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Delivery = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Delivery = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Delivery = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Delivery = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Delivery = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Delivery = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Delivery = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Delivery = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Delivery = where(DSL.notExists(select))
}
