/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.keys.DOCUMENT_TYPE_PKEY
import com.emented.printingstudio.jooq.keys.DOCUMENT_TYPE_VALUE_KEY
import com.emented.printingstudio.jooq.keys.DOCUMENT__DOCUMENT_TYPE_FKEY
import com.emented.printingstudio.jooq.tables.Document.DocumentPath
import com.emented.printingstudio.jooq.tables.records.DocumentTypeRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentType(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, DocumentTypeRecord>?,
    parentPath: InverseForeignKey<out Record, DocumentTypeRecord>?,
    aliased: Table<DocumentTypeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<DocumentTypeRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.document_type</code>
         */
        val DOCUMENT_TYPE: DocumentType = DocumentType()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DocumentTypeRecord> = DocumentTypeRecord::class.java

    /**
     * The column <code>public.document_type.id</code>.
     */
    val ID: TableField<DocumentTypeRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.document_type.value</code>.
     */
    val VALUE: TableField<DocumentTypeRecord, String?> = createField(DSL.name("value"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<DocumentTypeRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<DocumentTypeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<DocumentTypeRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.document_type</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.document_type</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.document_type</code> table reference
     */
    constructor(): this(DSL.name("document_type"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DocumentTypeRecord>?, parentPath: InverseForeignKey<out Record, DocumentTypeRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, DOCUMENT_TYPE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class DocumentTypePath : DocumentType, Path<DocumentTypeRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DocumentTypeRecord>?, parentPath: InverseForeignKey<out Record, DocumentTypeRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<DocumentTypeRecord>): super(alias, aliased)
        override fun `as`(alias: String): DocumentTypePath = DocumentTypePath(DSL.name(alias), this)
        override fun `as`(alias: Name): DocumentTypePath = DocumentTypePath(alias, this)
        override fun `as`(alias: Table<*>): DocumentTypePath = DocumentTypePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<DocumentTypeRecord, Long?> = super.getIdentity() as Identity<DocumentTypeRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<DocumentTypeRecord> = DOCUMENT_TYPE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<DocumentTypeRecord>> = listOf(DOCUMENT_TYPE_VALUE_KEY)

    private lateinit var _document: DocumentPath

    /**
     * Get the implicit to-many join path to the <code>public.document</code>
     * table
     */
    fun document(): DocumentPath {
        if (!this::_document.isInitialized)
            _document = DocumentPath(this, null, DOCUMENT__DOCUMENT_TYPE_FKEY.inverseKey)

        return _document;
    }

    val document: DocumentPath
        get(): DocumentPath = document()
    override fun `as`(alias: String): DocumentType = DocumentType(DSL.name(alias), this)
    override fun `as`(alias: Name): DocumentType = DocumentType(alias, this)
    override fun `as`(alias: Table<*>): DocumentType = DocumentType(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DocumentType = DocumentType(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DocumentType = DocumentType(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DocumentType = DocumentType(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): DocumentType = DocumentType(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): DocumentType = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): DocumentType = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): DocumentType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): DocumentType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): DocumentType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentType = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentType = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): DocumentType = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): DocumentType = where(DSL.notExists(select))
}
