/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.keys.FILAMENT_TYPE_PKEY
import com.emented.printingstudio.jooq.keys.FILAMENT_TYPE_VALUE_KEY
import com.emented.printingstudio.jooq.keys.MATERIAL__MATERIAL_TYPE_FKEY
import com.emented.printingstudio.jooq.tables.Material.MaterialPath
import com.emented.printingstudio.jooq.tables.records.FilamentTypeRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FilamentType(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, FilamentTypeRecord>?,
    parentPath: InverseForeignKey<out Record, FilamentTypeRecord>?,
    aliased: Table<FilamentTypeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<FilamentTypeRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.filament_type</code>
         */
        val FILAMENT_TYPE: FilamentType = FilamentType()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FilamentTypeRecord> = FilamentTypeRecord::class.java

    /**
     * The column <code>public.filament_type.id</code>.
     */
    val ID: TableField<FilamentTypeRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.filament_type.value</code>.
     */
    val VALUE: TableField<FilamentTypeRecord, String?> = createField(DSL.name("value"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<FilamentTypeRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<FilamentTypeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<FilamentTypeRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.filament_type</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.filament_type</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.filament_type</code> table reference
     */
    constructor(): this(DSL.name("filament_type"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FilamentTypeRecord>?, parentPath: InverseForeignKey<out Record, FilamentTypeRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, FILAMENT_TYPE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class FilamentTypePath : FilamentType, Path<FilamentTypeRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FilamentTypeRecord>?, parentPath: InverseForeignKey<out Record, FilamentTypeRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<FilamentTypeRecord>): super(alias, aliased)
        override fun `as`(alias: String): FilamentTypePath = FilamentTypePath(DSL.name(alias), this)
        override fun `as`(alias: Name): FilamentTypePath = FilamentTypePath(alias, this)
        override fun `as`(alias: Table<*>): FilamentTypePath = FilamentTypePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<FilamentTypeRecord, Long?> = super.getIdentity() as Identity<FilamentTypeRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<FilamentTypeRecord> = FILAMENT_TYPE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<FilamentTypeRecord>> = listOf(FILAMENT_TYPE_VALUE_KEY)

    private lateinit var _material: MaterialPath

    /**
     * Get the implicit to-many join path to the <code>public.material</code>
     * table
     */
    fun material(): MaterialPath {
        if (!this::_material.isInitialized)
            _material = MaterialPath(this, null, MATERIAL__MATERIAL_TYPE_FKEY.inverseKey)

        return _material;
    }

    val material: MaterialPath
        get(): MaterialPath = material()
    override fun `as`(alias: String): FilamentType = FilamentType(DSL.name(alias), this)
    override fun `as`(alias: Name): FilamentType = FilamentType(alias, this)
    override fun `as`(alias: Table<*>): FilamentType = FilamentType(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): FilamentType = FilamentType(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FilamentType = FilamentType(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FilamentType = FilamentType(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): FilamentType = FilamentType(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): FilamentType = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): FilamentType = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): FilamentType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): FilamentType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): FilamentType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): FilamentType = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): FilamentType = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): FilamentType = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): FilamentType = where(DSL.notExists(select))
}
