/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables

import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.keys.PAYMENT_PKEY
import com.emented.printingstudio.jooq.keys.PAYMENT__PAYMENT_STATUS_FKEY
import com.emented.printingstudio.jooq.keys.PAYMENT__PAYMENT_TYPE_FKEY
import com.emented.printingstudio.jooq.tables.records.PaymentRecord
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Payment(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PaymentRecord>?,
    aliased: Table<PaymentRecord>?,
    parameters: Array<Field<*>?>?,
) : TableImpl<PaymentRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
) {
    companion object {

        /**
         * The reference instance of <code>public.payment</code>
         */
        val PAYMENT = Payment()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PaymentRecord> = PaymentRecord::class.java

    /**
     * The column <code>public.payment.id</code>.
     */
    val ID: TableField<PaymentRecord, Long?> =
        createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.payment.type</code>.
     */
    val TYPE: TableField<PaymentRecord, Long?> =
        createField(DSL.name("type"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.payment.status</code>.
     */
    val STATUS: TableField<PaymentRecord, Long?> =
        createField(DSL.name("status"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.payment.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<PaymentRecord, OffsetDateTime?> =
        createField(DSL.name("creation_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.payment.update_timestamp</code>.
     */
    val UPDATE_TIMESTAMP: TableField<PaymentRecord, OffsetDateTime?> =
        createField(DSL.name("update_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PaymentRecord>?) : this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PaymentRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        aliased,
        parameters,
    )

    /**
     * Create an aliased <code>public.payment</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.payment</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.payment</code> table reference
     */
    constructor() : this(DSL.name("payment"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PaymentRecord>) : this(
        Internal.createPathAlias(
            child,
            key,
        ),
        child,
        key,
        PAYMENT,
        null,
    )

    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIdentity(): Identity<PaymentRecord, Long?> = super.getIdentity() as Identity<PaymentRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PaymentRecord> = PAYMENT_PKEY
    override fun getKeys(): List<UniqueKey<PaymentRecord>> = listOf(PAYMENT_PKEY)
    override fun getReferences(): List<ForeignKey<PaymentRecord, *>> =
        listOf(PAYMENT__PAYMENT_TYPE_FKEY, PAYMENT__PAYMENT_STATUS_FKEY)

    private lateinit var _paymentType: PaymentType
    private lateinit var _paymentStatus: PaymentStatus
    fun paymentType(): PaymentType {
        if (!this::_paymentType.isInitialized) {
            _paymentType = PaymentType(this, PAYMENT__PAYMENT_TYPE_FKEY)
        }

        return _paymentType
    }

    fun paymentStatus(): PaymentStatus {
        if (!this::_paymentStatus.isInitialized) {
            _paymentStatus = PaymentStatus(this, PAYMENT__PAYMENT_STATUS_FKEY)
        }

        return _paymentStatus
    }

    override fun `as`(alias: String): Payment = Payment(DSL.name(alias), this)
    override fun `as`(alias: Name): Payment = Payment(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Payment = Payment(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Payment = Payment(name, null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Long?, Long?, Long?, OffsetDateTime?, OffsetDateTime?> =
        super.fieldsRow() as Row5<Long?, Long?, Long?, OffsetDateTime?, OffsetDateTime?>
}
