/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.keys.ORDER__ORDER_PAYMENT_ID_FKEY
import com.emented.printingstudio.jooq.keys.PAYMENT_PKEY
import com.emented.printingstudio.jooq.keys.PAYMENT__PAYMENT_STATUS_FKEY
import com.emented.printingstudio.jooq.keys.PAYMENT__PAYMENT_TYPE_FKEY
import com.emented.printingstudio.jooq.tables.Order.OrderPath
import com.emented.printingstudio.jooq.tables.PaymentStatus.PaymentStatusPath
import com.emented.printingstudio.jooq.tables.PaymentType.PaymentTypePath
import com.emented.printingstudio.jooq.tables.records.PaymentRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Payment(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PaymentRecord>?,
    parentPath: InverseForeignKey<out Record, PaymentRecord>?,
    aliased: Table<PaymentRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PaymentRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.payment</code>
         */
        val PAYMENT: Payment = Payment()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PaymentRecord> = PaymentRecord::class.java

    /**
     * The column <code>public.payment.id</code>.
     */
    val ID: TableField<PaymentRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.payment.type</code>.
     */
    val TYPE: TableField<PaymentRecord, Long?> = createField(DSL.name("type"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.payment.status</code>.
     */
    val STATUS: TableField<PaymentRecord, Long?> = createField(DSL.name("status"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.payment.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<PaymentRecord, OffsetDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.payment.update_timestamp</code>.
     */
    val UPDATE_TIMESTAMP: TableField<PaymentRecord, OffsetDateTime?> = createField(DSL.name("update_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PaymentRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PaymentRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PaymentRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.payment</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.payment</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.payment</code> table reference
     */
    constructor(): this(DSL.name("payment"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PaymentRecord>?, parentPath: InverseForeignKey<out Record, PaymentRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PAYMENT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PaymentPath : Payment, Path<PaymentRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PaymentRecord>?, parentPath: InverseForeignKey<out Record, PaymentRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PaymentRecord>): super(alias, aliased)
        override fun `as`(alias: String): PaymentPath = PaymentPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PaymentPath = PaymentPath(alias, this)
        override fun `as`(alias: Table<*>): PaymentPath = PaymentPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<PaymentRecord, Long?> = super.getIdentity() as Identity<PaymentRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PaymentRecord> = PAYMENT_PKEY
    override fun getReferences(): List<ForeignKey<PaymentRecord, *>> = listOf(PAYMENT__PAYMENT_TYPE_FKEY, PAYMENT__PAYMENT_STATUS_FKEY)

    private lateinit var _paymentType: PaymentTypePath

    /**
     * Get the implicit join path to the <code>public.payment_type</code> table.
     */
    fun paymentType(): PaymentTypePath {
        if (!this::_paymentType.isInitialized)
            _paymentType = PaymentTypePath(this, PAYMENT__PAYMENT_TYPE_FKEY, null)

        return _paymentType;
    }

    val paymentType: PaymentTypePath
        get(): PaymentTypePath = paymentType()

    private lateinit var _paymentStatus: PaymentStatusPath

    /**
     * Get the implicit join path to the <code>public.payment_status</code>
     * table.
     */
    fun paymentStatus(): PaymentStatusPath {
        if (!this::_paymentStatus.isInitialized)
            _paymentStatus = PaymentStatusPath(this, PAYMENT__PAYMENT_STATUS_FKEY, null)

        return _paymentStatus;
    }

    val paymentStatus: PaymentStatusPath
        get(): PaymentStatusPath = paymentStatus()

    private lateinit var _order: OrderPath

    /**
     * Get the implicit to-many join path to the <code>public.order</code> table
     */
    fun order(): OrderPath {
        if (!this::_order.isInitialized)
            _order = OrderPath(this, null, ORDER__ORDER_PAYMENT_ID_FKEY.inverseKey)

        return _order;
    }

    val order: OrderPath
        get(): OrderPath = order()
    override fun `as`(alias: String): Payment = Payment(DSL.name(alias), this)
    override fun `as`(alias: Name): Payment = Payment(alias, this)
    override fun `as`(alias: Table<*>): Payment = Payment(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Payment = Payment(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Payment = Payment(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Payment = Payment(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Payment = Payment(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Payment = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Payment = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Payment = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Payment = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Payment = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Payment = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Payment = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Payment = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Payment = where(DSL.notExists(select))
}
