/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables


import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.keys.ORDER__ORDER_PRINT_SETTING_ID_FKEY
import com.emented.printingstudio.jooq.keys.PRINT_SETTING_PKEY
import com.emented.printingstudio.jooq.tables.Order.OrderPath
import com.emented.printingstudio.jooq.tables.records.PrintSettingRecord

import java.math.BigDecimal
import java.time.OffsetDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PrintSetting(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PrintSettingRecord>?,
    parentPath: InverseForeignKey<out Record, PrintSettingRecord>?,
    aliased: Table<PrintSettingRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PrintSettingRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.print_setting</code>
         */
        val PRINT_SETTING: PrintSetting = PrintSetting()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PrintSettingRecord> = PrintSettingRecord::class.java

    /**
     * The column <code>public.print_setting.id</code>.
     */
    val ID: TableField<PrintSettingRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.print_setting.description</code>.
     */
    val DESCRIPTION: TableField<PrintSettingRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.print_setting.price</code>.
     */
    val PRICE: TableField<PrintSettingRecord, BigDecimal?> = createField(DSL.name("price"), SQLDataType.NUMERIC(22, 2).nullable(false), this, "")

    /**
     * The column <code>public.print_setting.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<PrintSettingRecord, OffsetDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.print_setting.update_timestamp</code>.
     */
    val UPDATE_TIMESTAMP: TableField<PrintSettingRecord, OffsetDateTime?> = createField(DSL.name("update_timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PrintSettingRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PrintSettingRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PrintSettingRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.print_setting</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.print_setting</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.print_setting</code> table reference
     */
    constructor(): this(DSL.name("print_setting"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PrintSettingRecord>?, parentPath: InverseForeignKey<out Record, PrintSettingRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PRINT_SETTING, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PrintSettingPath : PrintSetting, Path<PrintSettingRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PrintSettingRecord>?, parentPath: InverseForeignKey<out Record, PrintSettingRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PrintSettingRecord>): super(alias, aliased)
        override fun `as`(alias: String): PrintSettingPath = PrintSettingPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PrintSettingPath = PrintSettingPath(alias, this)
        override fun `as`(alias: Table<*>): PrintSettingPath = PrintSettingPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<PrintSettingRecord, Long?> = super.getIdentity() as Identity<PrintSettingRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PrintSettingRecord> = PRINT_SETTING_PKEY

    private lateinit var _order: OrderPath

    /**
     * Get the implicit to-many join path to the <code>public.order</code> table
     */
    fun order(): OrderPath {
        if (!this::_order.isInitialized)
            _order = OrderPath(this, null, ORDER__ORDER_PRINT_SETTING_ID_FKEY.inverseKey)

        return _order;
    }

    val order: OrderPath
        get(): OrderPath = order()
    override fun `as`(alias: String): PrintSetting = PrintSetting(DSL.name(alias), this)
    override fun `as`(alias: Name): PrintSetting = PrintSetting(alias, this)
    override fun `as`(alias: Table<*>): PrintSetting = PrintSetting(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PrintSetting = PrintSetting(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PrintSetting = PrintSetting(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PrintSetting = PrintSetting(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PrintSetting = PrintSetting(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PrintSetting = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PrintSetting = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PrintSetting = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PrintSetting = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PrintSetting = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PrintSetting = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PrintSetting = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PrintSetting = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PrintSetting = where(DSL.notExists(select))
}
