/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables

import com.emented.printingstudio.jooq.Public
import com.emented.printingstudio.jooq.keys.SOCIAL_NETWORK_PKEY
import com.emented.printingstudio.jooq.tables.records.SocialNetworkRecord
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SocialNetwork(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SocialNetworkRecord>?,
    aliased: Table<SocialNetworkRecord>?,
    parameters: Array<Field<*>?>?,
) : TableImpl<SocialNetworkRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
) {
    companion object {

        /**
         * The reference instance of <code>public.social_network</code>
         */
        val SOCIAL_NETWORK = SocialNetwork()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SocialNetworkRecord> = SocialNetworkRecord::class.java

    /**
     * The column <code>public.social_network.id</code>.
     */
    val ID: TableField<SocialNetworkRecord, Long?> =
        createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.social_network.link</code>.
     */
    val LINK: TableField<SocialNetworkRecord, String?> =
        createField(DSL.name("link"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.social_network.type</code>.
     */
    val TYPE: TableField<SocialNetworkRecord, String?> =
        createField(DSL.name("type"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SocialNetworkRecord>?) : this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SocialNetworkRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        aliased,
        parameters,
    )

    /**
     * Create an aliased <code>public.social_network</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.social_network</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.social_network</code> table reference
     */
    constructor() : this(DSL.name("social_network"), null)

    constructor(
        child: Table<out Record>,
        key: ForeignKey<out Record, SocialNetworkRecord>,
    ) : this(Internal.createPathAlias(child, key), child, key, SOCIAL_NETWORK, null)

    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIdentity(): Identity<SocialNetworkRecord, Long?> =
        super.getIdentity() as Identity<SocialNetworkRecord, Long?>

    override fun getPrimaryKey(): UniqueKey<SocialNetworkRecord> = SOCIAL_NETWORK_PKEY
    override fun getKeys(): List<UniqueKey<SocialNetworkRecord>> = listOf(SOCIAL_NETWORK_PKEY)
    override fun `as`(alias: String): SocialNetwork = SocialNetwork(DSL.name(alias), this)
    override fun `as`(alias: Name): SocialNetwork = SocialNetwork(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SocialNetwork = SocialNetwork(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SocialNetwork = SocialNetwork(name, null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<Long?, String?, String?> = super.fieldsRow() as Row3<Long?, String?, String?>
}
