/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.routines


import com.emented.printingstudio.jooq.Public

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GetCustomerOrdersCount : AbstractRoutine<Long>("get_customer_orders_count", Public.PUBLIC, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter
         * <code>public.get_customer_orders_count.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>public.get_customer_orders_count.p_customer_id</code>.
         */
        val P_CUSTOMER_ID: Parameter<Long?> = Internal.createParameter("p_customer_id", SQLDataType.BIGINT, false, false)
    }

    init {
        returnParameter = GetCustomerOrdersCount.RETURN_VALUE
        addInParameter(GetCustomerOrdersCount.P_CUSTOMER_ID)
    }

    /**
     * Set the <code>p_customer_id</code> parameter IN value to the routine
     */
    fun setPCustomerId(value: Long?): Unit = setValue(GetCustomerOrdersCount.P_CUSTOMER_ID, value)

    /**
     * Set the <code>p_customer_id</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setPCustomerId(field: Field<Long?>): Unit {
        setField(GetCustomerOrdersCount.P_CUSTOMER_ID, field)
    }
}
