/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.routines


import com.emented.printingstudio.jooq.Public

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SetMaterialAvailabilityStatus : AbstractRoutine<java.lang.Void>("set_material_availability_status", Public.PUBLIC) {
    companion object {

        /**
         * The parameter
         * <code>public.set_material_availability_status.p_material_id</code>.
         */
        val P_MATERIAL_ID: Parameter<Long?> = Internal.createParameter("p_material_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>public.set_material_availability_status.p_availability_status</code>.
         */
        val P_AVAILABILITY_STATUS: Parameter<String?> = Internal.createParameter("p_availability_status", SQLDataType.VARCHAR, false, false)
    }

    init {
        addInParameter(SetMaterialAvailabilityStatus.P_MATERIAL_ID)
        addInParameter(SetMaterialAvailabilityStatus.P_AVAILABILITY_STATUS)
        setSQLUsable(false)
    }

    /**
     * Set the <code>p_material_id</code> parameter IN value to the routine
     */
    fun setPMaterialId(value: Long?): Unit = setValue(SetMaterialAvailabilityStatus.P_MATERIAL_ID, value)

    /**
     * Set the <code>p_availability_status</code> parameter IN value to the
     * routine
     */
    fun setPAvailabilityStatus(value: String?): Unit = setValue(SetMaterialAvailabilityStatus.P_AVAILABILITY_STATUS, value)
}
