/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.routines


import com.emented.printingstudio.jooq.Public

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SetOrderStatus : AbstractRoutine<java.lang.Void>("set_order_status", Public.PUBLIC) {
    companion object {

        /**
         * The parameter <code>public.set_order_status.p_order_id</code>.
         */
        val P_ORDER_ID: Parameter<Long?> = Internal.createParameter("p_order_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>public.set_order_status.p_status</code>.
         */
        val P_STATUS: Parameter<String?> = Internal.createParameter("p_status", SQLDataType.VARCHAR, false, false)
    }

    init {
        addInParameter(SetOrderStatus.P_ORDER_ID)
        addInParameter(SetOrderStatus.P_STATUS)
    }

    /**
     * Set the <code>p_order_id</code> parameter IN value to the routine
     */
    fun setPOrderId(value: Long?): Unit = setValue(SetOrderStatus.P_ORDER_ID, value)

    /**
     * Set the <code>p_status</code> parameter IN value to the routine
     */
    fun setPStatus(value: String?): Unit = setValue(SetOrderStatus.P_STATUS, value)
}
