/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.sequences

import com.emented.printingstudio.jooq.Public
import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

/**
 * The sequence <code>public.administrator_id_seq</code>
 */
val ADMINISTRATOR_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "administrator_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.availability_status_id_seq</code>
 */
val AVAILABILITY_STATUS_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "availability_status_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.business_info_id_seq</code>
 */
val BUSINESS_INFO_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "business_info_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.customer_id_seq</code>
 */
val CUSTOMER_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "customer_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.delivery_id_seq</code>
 */
val DELIVERY_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "delivery_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.delivery_status_id_seq</code>
 */
val DELIVERY_STATUS_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "delivery_status_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.delivery_type_id_seq</code>
 */
val DELIVERY_TYPE_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "delivery_type_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.document_id_seq</code>
 */
val DOCUMENT_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "document_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.document_type_id_seq</code>
 */
val DOCUMENT_TYPE_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "document_type_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.filament_type_id_seq</code>
 */
val FILAMENT_TYPE_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "filament_type_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.material_id_seq</code>
 */
val MATERIAL_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "material_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.order_id_seq</code>
 */
val ORDER_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "order_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.order_status_id_seq</code>
 */
val ORDER_STATUS_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "order_status_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.payment_id_seq</code>
 */
val PAYMENT_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "payment_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.payment_status_id_seq</code>
 */
val PAYMENT_STATUS_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "payment_status_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.payment_type_id_seq</code>
 */
val PAYMENT_TYPE_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "payment_type_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.print_setting_id_seq</code>
 */
val PRINT_SETTING_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "print_setting_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.social_network_id_seq</code>
 */
val SOCIAL_NETWORK_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "social_network_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)

/**
 * The sequence <code>public.user_id_seq</code>
 */
val USER_ID_SEQ: Sequence<Long> = Internal.createSequence(
    "user_id_seq",
    Public.PUBLIC,
    SQLDataType.BIGINT.nullable(false),
    null,
    null,
    null,
    null,
    false,
    null,
)
