/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables.records

import com.emented.printingstudio.jooq.tables.Administrator
import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AdministratorRecord() :
    UpdatableRecordImpl<AdministratorRecord>(Administrator.ADMINISTRATOR),
    Record4<Long?, Long?, OffsetDateTime?, OffsetDateTime?> {

    var id: Long?
        set(value) = set(0, value)
        get() = get(0) as Long?

    var userId: Long?
        set(value) = set(1, value)
        get() = get(1) as Long?

    var creationTimestamp: OffsetDateTime?
        set(value) = set(2, value)
        get() = get(2) as OffsetDateTime?

    var updateTimestamp: OffsetDateTime?
        set(value) = set(3, value)
        get() = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<Long?, Long?, OffsetDateTime?, OffsetDateTime?> =
        super.fieldsRow() as Row4<Long?, Long?, OffsetDateTime?, OffsetDateTime?>

    override fun valuesRow(): Row4<Long?, Long?, OffsetDateTime?, OffsetDateTime?> =
        super.valuesRow() as Row4<Long?, Long?, OffsetDateTime?, OffsetDateTime?>

    override fun field1(): Field<Long?> = Administrator.ADMINISTRATOR.ID
    override fun field2(): Field<Long?> = Administrator.ADMINISTRATOR.USER_ID
    override fun field3(): Field<OffsetDateTime?> = Administrator.ADMINISTRATOR.CREATION_TIMESTAMP
    override fun field4(): Field<OffsetDateTime?> = Administrator.ADMINISTRATOR.UPDATE_TIMESTAMP
    override fun component1(): Long? = id
    override fun component2(): Long? = userId
    override fun component3(): OffsetDateTime? = creationTimestamp
    override fun component4(): OffsetDateTime? = updateTimestamp
    override fun value1(): Long? = id
    override fun value2(): Long? = userId
    override fun value3(): OffsetDateTime? = creationTimestamp
    override fun value4(): OffsetDateTime? = updateTimestamp

    override fun value1(value: Long?): AdministratorRecord {
        this.id = value
        return this
    }

    override fun value2(value: Long?): AdministratorRecord {
        this.userId = value
        return this
    }

    override fun value3(value: OffsetDateTime?): AdministratorRecord {
        this.creationTimestamp = value
        return this
    }

    override fun value4(value: OffsetDateTime?): AdministratorRecord {
        this.updateTimestamp = value
        return this
    }

    override fun values(
        value1: Long?,
        value2: Long?,
        value3: OffsetDateTime?,
        value4: OffsetDateTime?,
    ): AdministratorRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised AdministratorRecord
     */
    constructor(
        id: Long? = null,
        userId: Long? = null,
        creationTimestamp: OffsetDateTime? = null,
        updateTimestamp: OffsetDateTime? = null,
    ) : this() {
        this.id = id
        this.userId = userId
        this.creationTimestamp = creationTimestamp
        this.updateTimestamp = updateTimestamp
    }
}
