/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables.records


import com.emented.printingstudio.jooq.tables.CustomerSocialNetwork

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CustomerSocialNetworkRecord() : UpdatableRecordImpl<CustomerSocialNetworkRecord>(CustomerSocialNetwork.CUSTOMER_SOCIAL_NETWORK) {

    open var customerId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var socialNetworkId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised CustomerSocialNetworkRecord
     */
    constructor(customerId: Long? = null, socialNetworkId: Long? = null): this() {
        this.customerId = customerId
        this.socialNetworkId = socialNetworkId
        resetChangedOnNotNull()
    }
}
