/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables.records

import com.emented.printingstudio.jooq.tables.Delivery
import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DeliveryRecord() :
    UpdatableRecordImpl<DeliveryRecord>(Delivery.DELIVERY),
    Record5<Long?, Long?, Long?, OffsetDateTime?, OffsetDateTime?> {

    var id: Long?
        set(value) = set(0, value)
        get() = get(0) as Long?

    var type: Long?
        set(value) = set(1, value)
        get() = get(1) as Long?

    var status: Long?
        set(value) = set(2, value)
        get() = get(2) as Long?

    var creationTimestamp: OffsetDateTime?
        set(value) = set(3, value)
        get() = get(3) as OffsetDateTime?

    var updateTimestamp: OffsetDateTime?
        set(value) = set(4, value)
        get() = get(4) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<Long?, Long?, Long?, OffsetDateTime?, OffsetDateTime?> =
        super.fieldsRow() as Row5<Long?, Long?, Long?, OffsetDateTime?, OffsetDateTime?>

    override fun valuesRow(): Row5<Long?, Long?, Long?, OffsetDateTime?, OffsetDateTime?> =
        super.valuesRow() as Row5<Long?, Long?, Long?, OffsetDateTime?, OffsetDateTime?>

    override fun field1(): Field<Long?> = Delivery.DELIVERY.ID
    override fun field2(): Field<Long?> = Delivery.DELIVERY.TYPE
    override fun field3(): Field<Long?> = Delivery.DELIVERY.STATUS
    override fun field4(): Field<OffsetDateTime?> = Delivery.DELIVERY.CREATION_TIMESTAMP
    override fun field5(): Field<OffsetDateTime?> = Delivery.DELIVERY.UPDATE_TIMESTAMP
    override fun component1(): Long? = id
    override fun component2(): Long? = type
    override fun component3(): Long? = status
    override fun component4(): OffsetDateTime? = creationTimestamp
    override fun component5(): OffsetDateTime? = updateTimestamp
    override fun value1(): Long? = id
    override fun value2(): Long? = type
    override fun value3(): Long? = status
    override fun value4(): OffsetDateTime? = creationTimestamp
    override fun value5(): OffsetDateTime? = updateTimestamp

    override fun value1(value: Long?): DeliveryRecord {
        this.id = value
        return this
    }

    override fun value2(value: Long?): DeliveryRecord {
        this.type = value
        return this
    }

    override fun value3(value: Long?): DeliveryRecord {
        this.status = value
        return this
    }

    override fun value4(value: OffsetDateTime?): DeliveryRecord {
        this.creationTimestamp = value
        return this
    }

    override fun value5(value: OffsetDateTime?): DeliveryRecord {
        this.updateTimestamp = value
        return this
    }

    override fun values(
        value1: Long?,
        value2: Long?,
        value3: Long?,
        value4: OffsetDateTime?,
        value5: OffsetDateTime?,
    ): DeliveryRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    /**
     * Create a detached, initialised DeliveryRecord
     */
    constructor(
        id: Long? = null,
        type: Long? = null,
        status: Long? = null,
        creationTimestamp: OffsetDateTime? = null,
        updateTimestamp: OffsetDateTime? = null,
    ) : this() {
        this.id = id
        this.type = type
        this.status = status
        this.creationTimestamp = creationTimestamp
        this.updateTimestamp = updateTimestamp
    }
}
