/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables.records


import com.emented.printingstudio.jooq.tables.Document

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentRecord() : UpdatableRecordImpl<DocumentRecord>(Document.DOCUMENT) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var type: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var url: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var orderId: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var creationTimestamp: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    open var updateTimestamp: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised DocumentRecord
     */
    constructor(id: Long? = null, type: Long? = null, url: String? = null, orderId: Long? = null, creationTimestamp: OffsetDateTime? = null, updateTimestamp: OffsetDateTime? = null): this() {
        this.id = id
        this.type = type
        this.url = url
        this.orderId = orderId
        this.creationTimestamp = creationTimestamp
        this.updateTimestamp = updateTimestamp
        resetChangedOnNotNull()
    }
}
