/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables.records

import com.emented.printingstudio.jooq.tables.Document
import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentRecord() :
    UpdatableRecordImpl<DocumentRecord>(Document.DOCUMENT),
    Record6<Long?, Long?, String?, Long?, OffsetDateTime?, OffsetDateTime?> {

    var id: Long?
        set(value) = set(0, value)
        get() = get(0) as Long?

    var type: Long?
        set(value) = set(1, value)
        get() = get(1) as Long?

    var url: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var orderId: Long?
        set(value) = set(3, value)
        get() = get(3) as Long?

    var creationTimestamp: OffsetDateTime?
        set(value) = set(4, value)
        get() = get(4) as OffsetDateTime?

    var updateTimestamp: OffsetDateTime?
        set(value) = set(5, value)
        get() = get(5) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row6<Long?, Long?, String?, Long?, OffsetDateTime?, OffsetDateTime?> =
        super.fieldsRow() as Row6<Long?, Long?, String?, Long?, OffsetDateTime?, OffsetDateTime?>

    override fun valuesRow(): Row6<Long?, Long?, String?, Long?, OffsetDateTime?, OffsetDateTime?> =
        super.valuesRow() as Row6<Long?, Long?, String?, Long?, OffsetDateTime?, OffsetDateTime?>

    override fun field1(): Field<Long?> = Document.DOCUMENT.ID
    override fun field2(): Field<Long?> = Document.DOCUMENT.TYPE
    override fun field3(): Field<String?> = Document.DOCUMENT.URL
    override fun field4(): Field<Long?> = Document.DOCUMENT.ORDER_ID
    override fun field5(): Field<OffsetDateTime?> = Document.DOCUMENT.CREATION_TIMESTAMP
    override fun field6(): Field<OffsetDateTime?> = Document.DOCUMENT.UPDATE_TIMESTAMP
    override fun component1(): Long? = id
    override fun component2(): Long? = type
    override fun component3(): String? = url
    override fun component4(): Long? = orderId
    override fun component5(): OffsetDateTime? = creationTimestamp
    override fun component6(): OffsetDateTime? = updateTimestamp
    override fun value1(): Long? = id
    override fun value2(): Long? = type
    override fun value3(): String? = url
    override fun value4(): Long? = orderId
    override fun value5(): OffsetDateTime? = creationTimestamp
    override fun value6(): OffsetDateTime? = updateTimestamp

    override fun value1(value: Long?): DocumentRecord {
        this.id = value
        return this
    }

    override fun value2(value: Long?): DocumentRecord {
        this.type = value
        return this
    }

    override fun value3(value: String?): DocumentRecord {
        this.url = value
        return this
    }

    override fun value4(value: Long?): DocumentRecord {
        this.orderId = value
        return this
    }

    override fun value5(value: OffsetDateTime?): DocumentRecord {
        this.creationTimestamp = value
        return this
    }

    override fun value6(value: OffsetDateTime?): DocumentRecord {
        this.updateTimestamp = value
        return this
    }

    override fun values(
        value1: Long?,
        value2: Long?,
        value3: String?,
        value4: Long?,
        value5: OffsetDateTime?,
        value6: OffsetDateTime?,
    ): DocumentRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised DocumentRecord
     */
    constructor(
        id: Long? = null,
        type: Long? = null,
        url: String? = null,
        orderId: Long? = null,
        creationTimestamp: OffsetDateTime? = null,
        updateTimestamp: OffsetDateTime? = null,
    ) : this() {
        this.id = id
        this.type = type
        this.url = url
        this.orderId = orderId
        this.creationTimestamp = creationTimestamp
        this.updateTimestamp = updateTimestamp
    }
}
