/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables.records


import com.emented.printingstudio.jooq.tables.GetTotalSalesPerMaterial

import java.math.BigDecimal

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GetTotalSalesPerMaterialRecord() : TableRecordImpl<GetTotalSalesPerMaterialRecord>(GetTotalSalesPerMaterial.GET_TOTAL_SALES_PER_MATERIAL) {

    open var materialType: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var salesRevenue: BigDecimal?
        set(value): Unit = set(1, value)
        get(): BigDecimal? = get(1) as BigDecimal?

    /**
     * Create a detached, initialised GetTotalSalesPerMaterialRecord
     */
    constructor(materialType: Long? = null, salesRevenue: BigDecimal? = null): this() {
        this.materialType = materialType
        this.salesRevenue = salesRevenue
        resetChangedOnNotNull()
    }
}
