/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables.records

import com.emented.printingstudio.jooq.tables.PrintSetting
import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl
import java.math.BigDecimal
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PrintSettingRecord() :
    UpdatableRecordImpl<PrintSettingRecord>(PrintSetting.PRINT_SETTING),
    Record5<Long?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?> {

    var id: Long?
        set(value) = set(0, value)
        get() = get(0) as Long?

    var description: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var price: BigDecimal?
        set(value) = set(2, value)
        get() = get(2) as BigDecimal?

    var creationTimestamp: OffsetDateTime?
        set(value) = set(3, value)
        get() = get(3) as OffsetDateTime?

    var updateTimestamp: OffsetDateTime?
        set(value) = set(4, value)
        get() = get(4) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<Long?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?> =
        super.fieldsRow() as Row5<Long?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?>

    override fun valuesRow(): Row5<Long?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?> =
        super.valuesRow() as Row5<Long?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?>

    override fun field1(): Field<Long?> = PrintSetting.PRINT_SETTING.ID
    override fun field2(): Field<String?> = PrintSetting.PRINT_SETTING.DESCRIPTION
    override fun field3(): Field<BigDecimal?> = PrintSetting.PRINT_SETTING.PRICE
    override fun field4(): Field<OffsetDateTime?> = PrintSetting.PRINT_SETTING.CREATION_TIMESTAMP
    override fun field5(): Field<OffsetDateTime?> = PrintSetting.PRINT_SETTING.UPDATE_TIMESTAMP
    override fun component1(): Long? = id
    override fun component2(): String? = description
    override fun component3(): BigDecimal? = price
    override fun component4(): OffsetDateTime? = creationTimestamp
    override fun component5(): OffsetDateTime? = updateTimestamp
    override fun value1(): Long? = id
    override fun value2(): String? = description
    override fun value3(): BigDecimal? = price
    override fun value4(): OffsetDateTime? = creationTimestamp
    override fun value5(): OffsetDateTime? = updateTimestamp

    override fun value1(value: Long?): PrintSettingRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): PrintSettingRecord {
        this.description = value
        return this
    }

    override fun value3(value: BigDecimal?): PrintSettingRecord {
        this.price = value
        return this
    }

    override fun value4(value: OffsetDateTime?): PrintSettingRecord {
        this.creationTimestamp = value
        return this
    }

    override fun value5(value: OffsetDateTime?): PrintSettingRecord {
        this.updateTimestamp = value
        return this
    }

    override fun values(
        value1: Long?,
        value2: String?,
        value3: BigDecimal?,
        value4: OffsetDateTime?,
        value5: OffsetDateTime?,
    ): PrintSettingRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    /**
     * Create a detached, initialised PrintSettingRecord
     */
    constructor(
        id: Long? = null,
        description: String? = null,
        price: BigDecimal? = null,
        creationTimestamp: OffsetDateTime? = null,
        updateTimestamp: OffsetDateTime? = null,
    ) : this() {
        this.id = id
        this.description = description
        this.price = price
        this.creationTimestamp = creationTimestamp
        this.updateTimestamp = updateTimestamp
    }
}
