/*
 * This file is generated by jOOQ.
 */
package com.emented.printingstudio.jooq.tables.records


import com.emented.printingstudio.jooq.tables.SocialNetwork

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SocialNetworkRecord() : UpdatableRecordImpl<SocialNetworkRecord>(SocialNetwork.SOCIAL_NETWORK) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var link: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var type: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised SocialNetworkRecord
     */
    constructor(id: Long? = null, link: String? = null, type: String? = null): this() {
        this.id = id
        this.link = link
        this.type = type
        resetChangedOnNotNull()
    }
}
